# Generated by Django 5.1.2 on 2024-10-24 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerostock',
            name='aeroID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aero_isd', to='api.aero'),
        ),
        migrations.AddField(
            model_name='componentstock',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aerostock',
            name='components',
            field=models.ManyToManyField(related_name='aero_stocks', to='api.componentstock'),
        ),
    ]
